### ISSUE TITLE
Default for mongoose update not really good (override true)

### ISSUE THREAD

**Issue by simonjoom** [feathersjs/feathers-mongoose#191]
I just wondering if override at true for update of service is very good
Exemple: 
i have in database 
{id= 1111, field1:"exist",field2:"exists",toupdate:false}

If i do service.update(1111,{toupdate:true}) 
the result give me {id= 1111, toupdate:false}

So i loose in my dtb field1:"exist",field2:"exists" 

i found the issue is due you put override true as a default option for mongoose

For me put override false will give me the appropriate result:
{id= 1111, field1:"exist",field2:"exists",toupdate:true}

Can you please answer it?
Regards

**Comment by eddyystop** [comment]
Why would you not use `service.patch` if you don't the entire record updated?

**Comment by simonjoom** [comment]
yes it what i did before in deed , but i found that update is less hard to code that patch only :)

**Comment by daffl** [comment]
This is by design for all database adapters and based on what a RESTful PUT is supposed to do. It is documented, e.g. in https://docs.feathersjs.com/api/services.html#updateid-data-params and https://docs.feathersjs.com/api/databases/common.html#service-methods

From the documentation:

> update(id, data, params) -> Promise - replaces the resource identified by id with data.

If you would like a different behaviour, you can always change the behaviour by e.g. mapping `.update` to `.patch` in a before hook.
