### ISSUE TITLE
Can't update field that is used as id

### ISSUE THREAD

**Issue by dottodot** [feathersjs/feathers-mongoose#202]
Not sure if this is a feathers-mongoose issue but I have a field called slug and this is set as my id field on my service. However if I try to update the slug value (i.e making a change for seo purposes) it doesn't update and stays the same. If I remove the custom id option from my service so I update using the default _id I can update the slug value.

Is this a bug or is there a way round this?

**Comment by daffl** [comment]
This has been introduce intentionally with the PR in https://github.com/feathersjs/feathers-mongoose/pull/65 after a longer discussion in https://github.com/feathersjs/feathers-mongodb/commit/5980ed6873851727db374f5a19e8d50ed1a94352#commitcomment-16280191

**Comment by dottodot** [comment]
Can you suggest anyway around it as don't think what I'm wanting to do should be prevented. The actual _id is still in place I just happen to use the slug field instead for nice url purposes.

**Comment by dottodot** [comment]
So is my only option to do something like this now? 

https://github.com/feathersjs/feathers-mongoose/pull/153#issuecomment-268329889

**Comment by ekryski** [comment]
@dottodot yes.

This is really a data modelling issue. In databases primary keys aren't really meant to be modified. If you are using a slug that gets modified as your main Id that's probably not ideal.

If you need to look up things by a slug in order to have fancy SEO or human friendly URLs you can easily add a hook to look up the record by the slug in a `find` call instead of a `get` and set `hook.result` to bypass the `get` call. In general, we tend to separate our API from our web app precisely for reasons like this (among others).

Another option is you can set up a vanity express route that takes a slug and calls your service internally (just remember that won't work over sockets).

```js
app.get('/things/:slug', (req, res, next) => {
  app.service('things').find({ query: { slug: req.params.slug }).then(next).catch(next);
});
```
