### ISSUE TITLE
How to override service methods

### ISSUE THREAD

**Issue by sgireddy** [feathersjs/feathers-mongoose#26]
By default feathers broadcast events to all connected clients when using socket.io mode, this could be fatal and feathers service provides a way to override default methods (created, find etc). How do I do the same with MongooseService?

**Comment by sgireddy** [comment]
found solution @ feathers-mongodb git, just needed to extend the serivce. 

var mongoose = require('feathers-mongoose');
var Proto = require('uberproto');

var MessageService = mongoose.Service.extend({
    created: function (data, params, callback) {
        //TODO Write logic
        return callback(null, data);
    },
    updated: function (data, params, callback) {                
        //TODO Write logic
        return callback(null, false);
    }
});

module.exports = function (modelName, schema, options) {
    return Proto.create.call(MessageService, modelName, schema, options);
};

module.exports.Service = MessageService;

**Comment by daffl** [comment]
That is correct. The newer versions will use ES6 classes instead of Uberproto but that is still in the works. 

Our preferred method though is through Hooks (https://github.com/feathersjs/feathers-hooks). For example, you could add a `created_at` and `updated_at` with extention like this:

```js
var mongoose = require('feathers-mongoose');
var Proto = require('uberproto');

var MessageService = mongoose.Service.extend({
    created: function (data, params, callback) {
        data.created_at = new Date();
        this._super(data, params, callback);
    },
    update: function (id, data, params, callback) {                
        data.created_at = new Date();
        this._super(data, params, callback);
    }
});
```

With hooks that would look like this:

```
function timestamp(name) {
  return function(hook, next) {
    hook.data[name] = new Date();
    next();
  }
}

app.service('users')
  // Add updated_at and created_at
  .before({
    create: timestamp('created_at'),
    update: timestamp('updated_at'),
    patch: timestamp('updated_at')
  });
```

The difference is that you can attach the `timestamp` hook to any service you'd like. I wrote about it in more detail at https://medium.com/all-about-feathersjs/api-service-composition-with-hooks-47af13aa6c01

**Comment by zealotrahl** [comment]
What if i need to search object by Mongose Object id type, i simply can not pass that from hook to service, it goes as string
