### ISSUE TITLE
Adding fields on update isn't currently possible

### ISSUE THREAD

**Issue by marshallswain** [feathersjs/feathers-mongoose#48]
Due to the loop here: https://github.com/feathersjs/feathers-mongoose/blob/master/src/service.js#L129
It's not possible to update a document and add a field at the same time.

@ekryski why are we setting fields to null?  What does that do?  Is it to leave the old fields alone?  That seems more like how patch should behave.

**Comment by daffl** [comment]
Wouldn't you use `patch` anyway?

**Comment by ekryski** [comment]
@marshallswain it's to fill any previous fields that aren't getting updated with **null**. I have a comment above that code but it must not be clear. We might be able to remove that but I vaguely remember their being issues with inserting a new object with the same ID as a previous one, and removing keys from an existing mongoose model.

I'm not sure your issue is a problem with the loop, or the feathers-mongoose driver for that matter. From what I remember Mongoose doesn't allow you to add fields to your model if they aren't defined on the schema, unless you set up a generic sub document.

**Comment by marshallswain** [comment]
My scenario is that I've added a field to my schema.  Now I'm trying to populate the field, but since we're only looping through the oldObject's keys (which doesn't include the new field) we're losing the new field's data.

I would use patch, but I haven't added patch support to can-connect, yet.  :)

**Comment by ekryski** [comment]
hmmm. There might be a bug there then. Maybe we should first loop through the old keys and "zero" them out with `null` (or try and remove them) if they don't exist in the new object and then just do `Object.assign({}, oldObjectNulledOut, newObject);`

**Comment by ekryski** [comment]
So looks like in the mongoose docs there is a better solution. We might actually be able to remove the extra `_get` call as well, which would be a nice performance boost.

```js
this.Model.update({ [this.id]: id }, newObject, {overwrite: true}).then((result) => { ... });
```

**Comment by marshallswain** [comment]
That looks good.

**Comment by jamesjnadeau** [comment]
:+1: that's what it should do IMHO

**Comment by ekryski** [comment]
@jamesjnadeau personally I think it should always overwrite it if you are using UPDATE, otherwise you should be using PATCH. I can already see @daffl saying "That's the RESTful way" ha ha.

So I think for now, let's keep that the default behaviour. We can keep the idea of making it configurable in the back of our mind, but I'm wary to add special params that are adapter specific, so if we are to add this it should be across all database adapters.

**Comment by jamesjnadeau** [comment]
You're right on both accounts! I switched patch and update in my head when I was thinking about this, sorry :) 
Would be nice if this was configurable like we talked about in #51, using options upon initialization....

**Comment by ekryski** [comment]
I'm thinking I'll fix this, this morning but it will be a major release, correcto @daffl?

**Comment by daffl** [comment]
That's a bug isn't it? Why major?

**Comment by ekryski** [comment]
I always get confused so I need someone to babysit my releases ha ha. It's a bug but it will be a breaking change if we default to overwriting objects.

**Comment by daffl** [comment]
Wait what was it doing before? The tests definitely expect the object to be replaced on `update` which it at least seemed to have been doing.

**Comment by marshallswain** [comment]
It was technically replacing the entire document, but didn’t support modifying the schema and adding attributes.

**Comment by ekryski** [comment]
Ok so we're just going to roll this into a minor release with #51 and #44.

**Comment by ekryski** [comment]
The only "breaking" difference will be that if you try and access fields that were removed they will be `undefined` and not `null`. Still falsy values and I doubt anyone is depending on them explicitly being `null` at this point.
