### ISSUE TITLE
$populate documentation

### ISSUE THREAD

**Issue by ansarizafar** [feathersjs/feathers-mongoose#75]
@ekryski I think $populate is not documented anywhere. I only want  few specific fields returned for the populated documents. I can do this with Mongoose like this

``` 
Story
.findOne({ title: /timex/i })
.populate('_creator', 'name') // only return the Persons name
.exec(function (err, story) {
  if (err) return handleError(err);
  
  console.log('The creator is %s', story._creator.name);
  // prints "The creator is Aaron"
  
  console.log('The creators age is %s', story._creator.age);
  // prints "The creators age is null'
})
```
I am using this code with feather client
```
customerService.find({query: { _id: '570e865e181048f80e87164d',  $populate: ['area'], $select: ['name','email','area']}}).then(customer => {
      this._customer = customer;
      console.log(customer);
   });
```
How can I only return name field from area service?

**Comment by ekryski** [comment]
@ansarizafar currently you'd have to do that in a hook or a series of hooks. Right now the query syntax doesn't support applying special query params to populated models.

In all honesty we are currently working out the best way to handle this. This is one of the strengths of GraphQL so we are evaluating that to see if it makes more sense to lean on GQL instead of adding this functionality ourselves. Stay tuned for that!

In the mean time you need to use a server side hook if you want to reduce what is returned form the request. If you are just trying to normal the response for your client (say a component only getting what it needs) you can add a client side hook for `after`, `find`.

I'm going to close this, but feel free to comment if that doesn't make sense. I think in reality this actually a couple different issues that still need to be figured out. Thanks for asking @ansarizafar!
