### ISSUE TITLE
_id is a string

### ISSUE THREAD

**Issue by robotnic** [feathersjs/feathers-mongoose#89]
I'm working with this data
http://parltrack.euwiki.org/dumps/ep_dossiers.json.xz

Structure
-------------
```
{
  total: 24791, limit: 5, skip: 0, 
  data:[
   {_id: "5754d722d1d1c561ca000009",…},
   {_id: "57465953d1d1c5270d000008",…}
  ]
}
```

As you see, the _id is a string and not a mongo key.

Workaround
-------------
db.dossiers.find().forEach(function(doc){doc.id=doc._id;db.dossiers.save(doc)})

Now I can set an index. 

Question
------------
Is there an easier way to do that?

Project
-------------
https://github.com/robotnic/eu-lobby

**Comment by daffl** [comment]
The ids will be converted to strings when sent to the client since JSON does not know the `ObjectId` type. When using Feathers services ids will be converted back and forth automatically but it looks like you are loading and saving to the database directly (without using a Mongoose model, too) which is not how the results are intended to be used.

**Comment by daffl** [comment]
Closing. Please feel free to reopen with more information.

**Comment by paulophp** [comment]
Hi I am using this hook to maintain a relation hasmany with mongo,
where tarefa has time, so time has tarefas_id : string from tarefas._id: ObjectId

I justo use services via socket to create and patch a time object when a tarefa is started or paused

Am I messing something? Because sometimes I pause a task and it just lose all the time objects saved with tarefas:_id  

code:

`return function(hook) {
    hook.hasmany = true;

    const data = hook.result.data
    const ids = [];
    for(var i in data)
    {
      if(ids.indexOf(data[i]._id) < 0)
        ids.push(data[i]._id)
    }

    return hook.app.service('times').find({
      query: { tarefa_id: {
        $in: ids
      } }
    }).then(u => {
      // console.log(u);
      for(var i in data)
      {
        var tempo = 0
        for(var x in u.data)
        {
          if(data[i]._id == u.data[x].tarefa_id)
          {
            var d1 = Date.parse(u.data[x].updatedAt)
            var d2 = Date.parse(u.data[x].createdAt)

            tempo =  +tempo + d1 - d2

            if(d1 == d2 && u.data[x].status == 'OPEN')
            {
              var d3 = new Date().getTime()


              tempo =  +tempo + d3 - d2

            }
          }
        }

        tempo = Math.floor(+tempo/1000)
        var estimativa = Math.floor(+data[i].tempo*3600)
        var porcentagem = Math.floor((tempo / estimativa) * 100)

        data[i].progress = {
          total:tempo,
          estimativa:estimativa,
          porcentagem
        }


      }
      hook.result.data = data

      // Always return the hook object or `undefined`
      return hook;
    });`
